# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProtoType_AnimalShoppingmall' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProtoType_AnimalShoppingmall
  pod 'Material', '~> 2.0'
  pod "PagingMenuController"
  pod 'Alamofire', '~> 4.4'
  pod 'PKHUD', '~> 4.0'
  pod 'AlamofireImage', '~> 3.1'

end




